-- Migration badges.json -> Supabase
-- 125 users, 551 badges

-- 1) Insert profiles
INSERT INTO profiles (username) VALUES
  ('01092001a'),
  ('3x68'),
  ('7ioki'),
  ('a2s_ndy'),
  ('abde_94440'),
  ('abdelillahle7'),
  ('akasinj'),
  ('alb26g'),
  ('amauary'),
  ('amtv56'),
  ('anoniymous_'),
  ('at0ss_'),
  ('aygot_'),
  ('ayoubshy04'),
  ('bahnkai__'),
  ('baymax_lgd'),
  ('bisphe_lynx'),
  ('blankaa_p'),
  ('bluediiemond'),
  ('byxotic2'),
  ('capita__7'),
  ('cathelonie'),
  ('d0ud_'),
  ('darouuk'),
  ('dinyx_izi'),
  ('divin_mk'),
  ('dryzzz_'),
  ('dvm_savaas'),
  ('e_senku'),
  ('eddyexpertub'),
  ('edouadouard_'),
  ('el_matte0'),
  ('elm_armins'),
  ('elm_ennio1808'),
  ('elm_greasy'),
  ('elm_louca'),
  ('elm_pika40'),
  ('elm_slm'),
  ('elm_strixparis'),
  ('elm_torch67'),
  ('elyrma'),
  ('enzo_ml_'),
  ('esstebann__'),
  ('fafeu76'),
  ('fiftyjad'),
  ('framboizz'),
  ('gabriel_unreal'),
  ('grg_samsung'),
  ('grimpeakstv'),
  ('grosdebilesiuuuuu'),
  ('harperevans'),
  ('henry2skalice'),
  ('hommepoli'),
  ('hugo971_nr7'),
  ('huliki44'),
  ('iam_aam4'),
  ('ic_linksy502'),
  ('jeageersb_grg'),
  ('jean__jacko'),
  ('juniordasie'),
  ('juste_aaron_'),
  ('kais917'),
  ('karzymmm'),
  ('kawsen0'),
  ('kc_tsuki95'),
  ('kurisui1'),
  ('kza_9'),
  ('lblns7'),
  ('legrandpanam54'),
  ('lenimois_'),
  ('lilya1220'),
  ('llea001'),
  ('lokayi'),
  ('lu_djo'),
  ('lucasledoge'),
  ('madelaed_iamgroot'),
  ('makira_cf'),
  ('marc_gjrt'),
  ('mathis25twitch'),
  ('mattouxe_'),
  ('mielox121'),
  ('milavabo'),
  ('moone12345667788'),
  ('mrsleyz'),
  ('mrwan_nk'),
  ('nathanmp23'),
  ('natos_nk'),
  ('neiko_jojo'),
  ('nino_seijuro'),
  ('nussaduxii'),
  ('nzoww___'),
  ('occxlt'),
  ('os_younes'),
  ('owksama'),
  ('ozan_937'),
  ('pa2goute'),
  ('paaizenn'),
  ('papoonu82'),
  ('payzy__'),
  ('pneuuumaaatiiikz'),
  ('polux_prod'),
  ('pooj585'),
  ('prodnes'),
  ('ramka_213'),
  ('rocket_bas'),
  ('s_i_j_u'),
  ('sandy13000'),
  ('senzu_coca'),
  ('sk_takashii'),
  ('slash609'),
  ('sonay__'),
  ('tarteen_'),
  ('ton_daron_l_epicier'),
  ('towaxxx'),
  ('tvabdou'),
  ('uncongolaisdanslebinks'),
  ('varchess'),
  ('y_d69'),
  ('yanissou92i'),
  ('yannx27'),
  ('yklawb'),
  ('yukofnr'),
  ('yuralerat'),
  ('zenox_tempest'),
  ('zeyne_e');

-- 2) Insert badges
INSERT INTO badges (username, season, rarity) VALUES
  ('01092001a', 'saison2', 'EPIC'),
  ('3x68', 'saison2', 'COMMON'),
  ('3x68', 'saison2', 'COMMON'),
  ('3x68', 'saison2', 'RARE'),
  ('3x68', 'saison2', 'COMMON'),
  ('3x68', 'saison2', 'RARE'),
  ('7ioki', 'saison2', 'COMMON'),
  ('a2s_ndy', 'saison1', 'COMMON'),
  ('a2s_ndy', 'saison2', 'COMMON'),
  ('abde_94440', 'saison1', 'COMMON'),
  ('abdelillahle7', 'saison1', 'COMMON'),
  ('abdelillahle7', 'saison2', 'EPIC'),
  ('akasinj', 'saison1', 'COMMON'),
  ('akasinj', 'saison1', 'EPIC'),
  ('akasinj', 'saison1', 'COMMON'),
  ('akasinj', 'saison1', 'COMMON'),
  ('akasinj', 'saison1', 'COMMON'),
  ('akasinj', 'saison1', 'COMMON'),
  ('akasinj', 'saison1', 'COMMON'),
  ('akasinj', 'saison1', 'COMMON'),
  ('akasinj', 'saison1', 'RARE'),
  ('akasinj', 'saison1', 'LEGENDARY'),
  ('akasinj', 'saison1', 'COMMON'),
  ('akasinj', 'saison1', 'COMMON'),
  ('akasinj', 'saison1', 'EPIC'),
  ('akasinj', 'saison1', 'EPIC'),
  ('akasinj', 'saison1', 'EPIC'),
  ('akasinj', 'saison1', 'RARE'),
  ('akasinj', 'saison1', 'RARE'),
  ('akasinj', 'saison1', 'COMMON'),
  ('akasinj', 'saison1', 'RARE'),
  ('akasinj', 'saison1', 'RARE'),
  ('akasinj', 'saison1', 'COMMON'),
  ('akasinj', 'saison1', 'RARE'),
  ('akasinj', 'saison1', 'RARE'),
  ('akasinj', 'saison1', 'RARE'),
  ('akasinj', 'saison1', 'LEGENDARY'),
  ('akasinj', 'saison1', 'COMMON'),
  ('akasinj', 'saison1', 'EPIC'),
  ('akasinj', 'saison1', 'LEGENDARY'),
  ('akasinj', 'saison1', 'COMMON'),
  ('akasinj', 'saison2', 'UNIQUE'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'LEGENDARY'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'LEGENDARY'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'RARE'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'COMMON'),
  ('akasinj', 'saison2', 'EPIC'),
  ('akasinj', 'saison2', 'RARE'),
  ('alb26g', 'saison2', 'EPIC'),
  ('amauary', 'saison2', 'COMMON'),
  ('amtv56', 'saison1', 'RARE'),
  ('amtv56', 'saison2', 'COMMON'),
  ('anoniymous_', 'saison1', 'COMMON'),
  ('anoniymous_', 'saison2', 'RARE'),
  ('anoniymous_', 'saison2', 'COMMON'),
  ('anoniymous_', 'saison2', 'RARE'),
  ('anoniymous_', 'saison2', 'EPIC'),
  ('anoniymous_', 'saison2', 'COMMON'),
  ('at0ss_', 'saison2', 'COMMON'),
  ('aygot_', 'saison1', 'COMMON'),
  ('ayoubshy04', 'saison2', 'RARE'),
  ('bahnkai__', 'saison1', 'RARE'),
  ('bahnkai__', 'saison1', 'COMMON'),
  ('bahnkai__', 'saison1', 'EPIC'),
  ('bahnkai__', 'saison1', 'LEGENDARY'),
  ('bahnkai__', 'saison1', 'UNIQUE'),
  ('bahnkai__', 'saison1', 'RARE'),
  ('baymax_lgd', 'saison2', 'EPIC'),
  ('bisphe_lynx', 'saison2', 'EPIC'),
  ('bisphe_lynx', 'saison2', 'COMMON'),
  ('blankaa_p', 'saison2', 'RARE'),
  ('bluediiemond', 'saison1', 'RARE'),
  ('bluediiemond', 'saison1', 'COMMON'),
  ('bluediiemond', 'saison2', 'COMMON'),
  ('byxotic2', 'saison1', 'RARE'),
  ('capita__7', 'saison2', 'EPIC'),
  ('capita__7', 'saison2', 'RARE'),
  ('cathelonie', 'saison1', 'EPIC'),
  ('cathelonie', 'saison1', 'COMMON'),
  ('cathelonie', 'saison2', 'RARE'),
  ('cathelonie', 'saison2', 'RARE'),
  ('d0ud_', 'saison1', 'EPIC'),
  ('d0ud_', 'saison2', 'COMMON'),
  ('d0ud_', 'saison2', 'LEGENDARY'),
  ('d0ud_', 'saison2', 'RARE'),
  ('d0ud_', 'saison2', 'RARE'),
  ('d0ud_', 'saison2', 'COMMON'),
  ('d0ud_', 'saison2', 'EPIC'),
  ('d0ud_', 'saison2', 'LEGENDARY'),
  ('darouuk', 'saison1', 'EPIC'),
  ('darouuk', 'saison1', 'RARE'),
  ('darouuk', 'saison1', 'COMMON'),
  ('darouuk', 'saison1', 'EPIC'),
  ('darouuk', 'saison1', 'RARE'),
  ('darouuk', 'saison1', 'COMMON'),
  ('darouuk', 'saison1', 'LEGENDARY'),
  ('darouuk', 'saison1', 'RARE'),
  ('darouuk', 'saison1', 'LEGENDARY'),
  ('darouuk', 'saison1', 'LEGENDARY'),
  ('dinyx_izi', 'saison2', 'EPIC'),
  ('divin_mk', 'saison2', 'EPIC'),
  ('divin_mk', 'saison2', 'COMMON'),
  ('divin_mk', 'saison2', 'COMMON'),
  ('divin_mk', 'saison2', 'COMMON'),
  ('divin_mk', 'saison2', 'COMMON'),
  ('divin_mk', 'saison2', 'EPIC'),
  ('divin_mk', 'saison2', 'COMMON'),
  ('divin_mk', 'saison2', 'COMMON'),
  ('divin_mk', 'saison2', 'COMMON'),
  ('divin_mk', 'saison2', 'RARE'),
  ('divin_mk', 'saison2', 'LEGENDARY'),
  ('divin_mk', 'saison2', 'EPIC'),
  ('divin_mk', 'saison2', 'COMMON'),
  ('divin_mk', 'saison2', 'RARE'),
  ('divin_mk', 'saison2', 'EPIC'),
  ('dryzzz_', 'saison1', 'COMMON'),
  ('dvm_savaas', 'saison2', 'COMMON'),
  ('e_senku', 'saison1', 'COMMON'),
  ('e_senku', 'saison1', 'RARE'),
  ('e_senku', 'saison1', 'COMMON'),
  ('eddyexpertub', 'saison1', 'EPIC'),
  ('edouadouard_', 'saison2', 'COMMON'),
  ('el_matte0', 'saison1', 'RARE'),
  ('el_matte0', 'saison1', 'COMMON'),
  ('elm_armins', 'saison1', 'COMMON'),
  ('elm_armins', 'saison1', 'EPIC'),
  ('elm_armins', 'saison1', 'EPIC'),
  ('elm_armins', 'saison1', 'COMMON'),
  ('elm_armins', 'saison2', 'RARE'),
  ('elm_armins', 'saison2', 'COMMON'),
  ('elm_ennio1808', 'saison1', 'EPIC'),
  ('elm_greasy', 'saison2', 'COMMON'),
  ('elm_greasy', 'saison2', 'LEGENDARY'),
  ('elm_greasy', 'saison2', 'EPIC'),
  ('elm_greasy', 'saison2', 'COMMON'),
  ('elm_greasy', 'saison2', 'RARE'),
  ('elm_louca', 'saison1', 'RARE'),
  ('elm_louca', 'saison2', 'EPIC'),
  ('elm_pika40', 'saison2', 'COMMON'),
  ('elm_pika40', 'saison2', 'RARE'),
  ('elm_pika40', 'saison2', 'EPIC'),
  ('elm_pika40', 'saison2', 'RARE'),
  ('elm_pika40', 'saison2', 'COMMON'),
  ('elm_pika40', 'saison2', 'COMMON'),
  ('elm_pika40', 'saison2', 'EPIC'),
  ('elm_pika40', 'saison2', 'RARE'),
  ('elm_pika40', 'saison2', 'COMMON'),
  ('elm_pika40', 'saison2', 'COMMON'),
  ('elm_slm', 'saison1', 'EPIC'),
  ('elm_slm', 'saison2', 'RARE'),
  ('elm_slm', 'saison2', 'EPIC'),
  ('elm_strixparis', 'saison1', 'RARE'),
  ('elm_torch67', 'saison1', 'RARE'),
  ('elm_torch67', 'saison1', 'RARE'),
  ('elm_torch67', 'saison2', 'RARE'),
  ('elm_torch67', 'saison2', 'EPIC'),
  ('elm_torch67', 'saison2', 'EPIC'),
  ('elm_torch67', 'saison2', 'EPIC'),
  ('elyrma', 'saison1', 'COMMON'),
  ('elyrma', 'saison1', 'RARE'),
  ('enzo_ml_', 'saison2', 'EPIC'),
  ('esstebann__', 'saison1', 'RARE'),
  ('esstebann__', 'saison1', 'EPIC'),
  ('fafeu76', 'saison1', 'RARE'),
  ('fiftyjad', 'saison1', 'COMMON'),
  ('fiftyjad', 'saison1', 'LEGENDARY'),
  ('fiftyjad', 'saison1', 'RARE'),
  ('framboizz', 'saison2', 'EPIC'),
  ('gabriel_unreal', 'saison2', 'COMMON'),
  ('grg_samsung', 'saison1', 'RARE'),
  ('grg_samsung', 'saison2', 'RARE'),
  ('grimpeakstv', 'saison2', 'EPIC'),
  ('grosdebilesiuuuuu', 'saison1', 'COMMON'),
  ('harperevans', 'saison2', 'COMMON'),
  ('henry2skalice', 'saison2', 'RARE'),
  ('henry2skalice', 'saison2', 'COMMON'),
  ('hommepoli', 'saison1', 'COMMON'),
  ('hommepoli', 'saison1', 'EPIC'),
  ('hommepoli', 'saison1', 'LEGENDARY'),
  ('hommepoli', 'saison1', 'COMMON'),
  ('hugo971_nr7', 'saison2', 'COMMON'),
  ('huliki44', 'saison2', 'EPIC'),
  ('iam_aam4', 'saison1', 'RARE'),
  ('iam_aam4', 'saison2', 'RARE'),
  ('ic_linksy502', 'saison2', 'COMMON'),
  ('jeageersb_grg', 'saison2', 'COMMON'),
  ('jean__jacko', 'saison2', 'COMMON'),
  ('juniordasie', 'saison2', 'LEGENDARY'),
  ('juniordasie', 'saison2', 'COMMON'),
  ('juste_aaron_', 'saison2', 'RARE'),
  ('kais917', 'saison1', 'COMMON'),
  ('karzymmm', 'saison1', 'COMMON'),
  ('kc_tsuki95', 'saison2', 'COMMON'),
  ('kurisui1', 'saison1', 'COMMON'),
  ('kurisui1', 'saison1', 'RARE'),
  ('kurisui1', 'saison2', 'COMMON'),
  ('kurisui1', 'saison2', 'COMMON'),
  ('kza_9', 'saison1', 'LEGENDARY'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison1', 'LEGENDARY'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison1', 'RARE'),
  ('lblns7', 'saison1', 'LEGENDARY'),
  ('lblns7', 'saison1', 'RARE'),
  ('lblns7', 'saison1', 'RARE'),
  ('lblns7', 'saison1', 'RARE'),
  ('lblns7', 'saison1', 'RARE'),
  ('lblns7', 'saison1', 'EPIC'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison1', 'COMMON'),
  ('lblns7', 'saison2', 'COMMON'),
  ('lblns7', 'saison2', 'EPIC'),
  ('lblns7', 'saison2', 'COMMON'),
  ('lblns7', 'saison2', 'COMMON'),
  ('lblns7', 'saison2', 'RARE'),
  ('lblns7', 'saison2', 'COMMON'),
  ('lblns7', 'saison2', 'RARE'),
  ('lblns7', 'saison2', 'LEGENDARY'),
  ('lblns7', 'saison2', 'COMMON'),
  ('legrandpanam54', 'saison2', 'EPIC'),
  ('lenimois_', 'saison2', 'RARE'),
  ('lilya1220', 'saison1', 'COMMON'),
  ('lilya1220', 'saison1', 'RARE'),
  ('lilya1220', 'saison1', 'COMMON'),
  ('lilya1220', 'saison2', 'EPIC'),
  ('lilya1220', 'saison2', 'COMMON'),
  ('lilya1220', 'saison2', 'RARE'),
  ('llea001', 'saison1', 'RARE'),
  ('llea001', 'saison2', 'COMMON'),
  ('lokayi', 'saison2', 'RARE'),
  ('lu_djo', 'saison2', 'RARE'),
  ('lucasledoge', 'saison2', 'RARE'),
  ('madelaed_iamgroot', 'saison2', 'COMMON'),
  ('madelaed_iamgroot', 'saison2', 'RARE'),
  ('madelaed_iamgroot', 'saison2', 'COMMON'),
  ('makira_cf', 'saison2', 'RARE'),
  ('marc_gjrt', 'saison2', 'RARE'),
  ('mathis25twitch', 'saison2', 'RARE'),
  ('mattouxe_', 'saison1', 'COMMON'),
  ('mattouxe_', 'saison2', 'COMMON'),
  ('mattouxe_', 'saison2', 'RARE'),
  ('mattouxe_', 'saison2', 'LEGENDARY'),
  ('mielox121', 'saison2', 'COMMON'),
  ('mielox121', 'saison2', 'RARE'),
  ('milavabo', 'saison2', 'COMMON'),
  ('moone12345667788', 'saison2', 'RARE'),
  ('mrsleyz', 'saison1', 'RARE'),
  ('mrsleyz', 'saison1', 'COMMON'),
  ('mrsleyz', 'saison2', 'EPIC'),
  ('mrwan_nk', 'saison1', 'COMMON'),
  ('mrwan_nk', 'saison1', 'RARE'),
  ('mrwan_nk', 'saison2', 'COMMON'),
  ('nathanmp23', 'saison1', 'COMMON'),
  ('natos_nk', 'saison1', 'COMMON'),
  ('neiko_jojo', 'saison2', 'COMMON'),
  ('nino_seijuro', 'saison2', 'EPIC'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'EPIC'),
  ('nussaduxii', 'saison2', 'RARE'),
  ('nussaduxii', 'saison2', 'RARE'),
  ('nussaduxii', 'saison2', 'RARE'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'RARE'),
  ('nussaduxii', 'saison2', 'RARE'),
  ('nussaduxii', 'saison2', 'EPIC'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'EPIC'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'RARE'),
  ('nussaduxii', 'saison2', 'RARE'),
  ('nussaduxii', 'saison2', 'RARE'),
  ('nussaduxii', 'saison2', 'RARE'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'RARE'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nussaduxii', 'saison2', 'COMMON'),
  ('nzoww___', 'saison2', 'COMMON'),
  ('nzoww___', 'saison2', 'LEGENDARY'),
  ('occxlt', 'saison1', 'COMMON'),
  ('occxlt', 'saison1', 'COMMON'),
  ('occxlt', 'saison1', 'COMMON'),
  ('occxlt', 'saison2', 'COMMON'),
  ('occxlt', 'saison2', 'RARE'),
  ('occxlt', 'saison2', 'COMMON'),
  ('os_younes', 'saison1', 'COMMON'),
  ('owksama', 'saison1', 'RARE'),
  ('owksama', 'saison1', 'EPIC'),
  ('owksama', 'saison1', 'COMMON'),
  ('owksama', 'saison1', 'COMMON'),
  ('owksama', 'saison1', 'LEGENDARY'),
  ('ozan_937', 'saison1', 'EPIC'),
  ('pa2goute', 'saison1', 'COMMON'),
  ('paaizenn', 'saison2', 'COMMON'),
  ('papoonu82', 'saison1', 'COMMON'),
  ('payzy__', 'saison1', 'COMMON'),
  ('payzy__', 'saison2', 'RARE'),
  ('payzy__', 'saison2', 'COMMON'),
  ('pneuuumaaatiiikz', 'saison2', 'COMMON'),
  ('pneuuumaaatiiikz', 'saison2', 'RARE'),
  ('pneuuumaaatiiikz', 'saison2', 'EPIC'),
  ('pneuuumaaatiiikz', 'saison2', 'COMMON'),
  ('polux_prod', 'saison1', 'RARE'),
  ('polux_prod', 'saison1', 'RARE'),
  ('pooj585', 'saison1', 'RARE'),
  ('pooj585', 'saison2', 'RARE'),
  ('pooj585', 'saison2', 'RARE'),
  ('prodnes', 'saison2', 'COMMON'),
  ('prodnes', 'saison2', 'COMMON'),
  ('ramka_213', 'saison1', 'COMMON'),
  ('rocket_bas', 'saison1', 'COMMON'),
  ('rocket_bas', 'saison2', 'RARE'),
  ('s_i_j_u', 'saison2', 'EPIC'),
  ('sandy13000', 'saison2', 'RARE'),
  ('senzu_coca', 'saison1', 'RARE'),
  ('senzu_coca', 'saison2', 'COMMON'),
  ('sk_takashii', 'saison1', 'LEGENDARY'),
  ('sk_takashii', 'saison2', 'COMMON'),
  ('sk_takashii', 'saison2', 'COMMON'),
  ('sk_takashii', 'saison2', 'COMMON'),
  ('slash609', 'saison1', 'UNIQUE'),
  ('slash609', 'saison1', 'RARE'),
  ('slash609', 'saison1', 'RARE'),
  ('slash609', 'saison1', 'COMMON'),
  ('slash609', 'saison1', 'COMMON'),
  ('slash609', 'saison1', 'LEGENDARY'),
  ('slash609', 'saison1', 'RARE'),
  ('slash609', 'saison1', 'COMMON'),
  ('slash609', 'saison1', 'EPIC'),
  ('slash609', 'saison1', 'EPIC'),
  ('slash609', 'saison1', 'COMMON'),
  ('slash609', 'saison1', 'COMMON'),
  ('slash609', 'saison1', 'COMMON'),
  ('slash609', 'saison1', 'COMMON'),
  ('slash609', 'saison1', 'COMMON'),
  ('slash609', 'saison1', 'EPIC'),
  ('slash609', 'saison1', 'COMMON'),
  ('slash609', 'saison1', 'COMMON'),
  ('slash609', 'saison1', 'COMMON'),
  ('slash609', 'saison1', 'COMMON'),
  ('slash609', 'saison1', 'RARE'),
  ('slash609', 'saison1', 'RARE'),
  ('slash609', 'saison1', 'COMMON'),
  ('slash609', 'saison1', 'RARE'),
  ('slash609', 'saison1', 'RARE'),
  ('slash609', 'saison1', 'EPIC'),
  ('slash609', 'saison1', 'RARE'),
  ('slash609', 'saison1', 'RARE'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'RARE'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'EPIC'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'EPIC'),
  ('slash609', 'saison2', 'RARE'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'RARE'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'EPIC'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'RARE'),
  ('slash609', 'saison2', 'RARE'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'LEGENDARY'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'EPIC'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'RARE'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'EPIC'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'LEGENDARY'),
  ('slash609', 'saison2', 'EPIC'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'RARE'),
  ('slash609', 'saison2', 'RARE'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'EPIC'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'RARE'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'RARE'),
  ('slash609', 'saison2', 'RARE'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'RARE'),
  ('slash609', 'saison2', 'EPIC'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'EPIC'),
  ('slash609', 'saison2', 'EPIC'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'RARE'),
  ('slash609', 'saison2', 'LEGENDARY'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('slash609', 'saison2', 'COMMON'),
  ('sonay__', 'saison2', 'COMMON'),
  ('sonay__', 'saison2', 'COMMON'),
  ('tarteen_', 'saison1', 'RARE'),
  ('ton_daron_l_epicier', 'saison1', 'EPIC'),
  ('ton_daron_l_epicier', 'saison1', 'RARE'),
  ('ton_daron_l_epicier', 'saison1', 'COMMON'),
  ('ton_daron_l_epicier', 'saison1', 'RARE'),
  ('ton_daron_l_epicier', 'saison1', 'RARE'),
  ('ton_daron_l_epicier', 'saison1', 'COMMON'),
  ('ton_daron_l_epicier', 'saison1', 'RARE'),
  ('ton_daron_l_epicier', 'saison1', 'RARE'),
  ('ton_daron_l_epicier', 'saison1', 'COMMON'),
  ('ton_daron_l_epicier', 'saison1', 'RARE'),
  ('ton_daron_l_epicier', 'saison1', 'RARE'),
  ('ton_daron_l_epicier', 'saison1', 'RARE'),
  ('ton_daron_l_epicier', 'saison2', 'COMMON'),
  ('ton_daron_l_epicier', 'saison2', 'RARE'),
  ('ton_daron_l_epicier', 'saison2', 'COMMON'),
  ('ton_daron_l_epicier', 'saison2', 'EPIC'),
  ('ton_daron_l_epicier', 'saison2', 'RARE'),
  ('ton_daron_l_epicier', 'saison2', 'EPIC'),
  ('towaxxx', 'saison1', 'COMMON'),
  ('towaxxx', 'saison2', 'LEGENDARY'),
  ('tvabdou', 'saison1', 'RARE'),
  ('tvabdou', 'saison2', 'RARE'),
  ('tvabdou', 'saison2', 'COMMON'),
  ('tvabdou', 'saison2', 'COMMON'),
  ('uncongolaisdanslebinks', 'saison2', 'RARE'),
  ('varchess', 'saison1', 'COMMON'),
  ('y_d69', 'saison2', 'RARE'),
  ('yanissou92i', 'saison2', 'COMMON'),
  ('yanissou92i', 'saison2', 'EPIC'),
  ('yanissou92i', 'saison2', 'EPIC'),
  ('yanissou92i', 'saison2', 'COMMON'),
  ('yanissou92i', 'saison2', 'EPIC'),
  ('yanissou92i', 'saison2', 'RARE'),
  ('yanissou92i', 'saison2', 'COMMON'),
  ('yanissou92i', 'saison2', 'RARE'),
  ('yanissou92i', 'saison2', 'COMMON'),
  ('yanissou92i', 'saison2', 'COMMON'),
  ('yanissou92i', 'saison2', 'COMMON'),
  ('yanissou92i', 'saison2', 'COMMON'),
  ('yanissou92i', 'saison2', 'COMMON'),
  ('yanissou92i', 'saison2', 'COMMON'),
  ('yanissou92i', 'saison2', 'RARE'),
  ('yannx27', 'saison2', 'COMMON'),
  ('yklawb', 'saison1', 'LEGENDARY'),
  ('yukofnr', 'saison1', 'COMMON'),
  ('yuralerat', 'saison2', 'COMMON'),
  ('zenox_tempest', 'saison2', 'RARE'),
  ('zeyne_e', 'saison2', 'COMMON');

-- Done: 125 profiles, 551 badges inserted